
cassandra:
  image: cassandra:3.7
  environment:
    - ENV MAX_HEAP_SIZE=1G
    - ENV HEAP_NEWSIZE=400M
  ports:
    - "7000:7000"
    - "7001:7001"
    - "7199:7199"
    - "9042:9042"
    - "9160:9160"
